name: secret example
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  download:
      name: Display secret
      runs-on: ubuntu-latest
      steps:
      - name: retrieve secret
        env: 
         username: ${{ secrets.USERNAME }}
        run: |
          echo The result is $username
