name: secret example
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  retrieve username:
      name: Display username
      runs-on: ubuntu-latest
      steps:
      - name: retrieve username
        env: 
         username: ${{ secrets.USERNAME }}
        run: |
          echo The result is $username
  retrieve password:
    name: Display password
    runs-on: ubuntu-latest
    steps:
    - name: retrieve password
      env: 
       password: ${{ secrets.PASSWORD }}
      run: |
        echo The result is $password
