name: upload example
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  upload:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    
    steps:
    - shell: bash
      run: |
        expr 3 + 7 > output.log
    - name: Upload output file
      uses: actions/upload-artifact@v1
      with:
        name: output-log-file
        path: output.log
  download:
      name: Display results
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - name: download file uploaded from upload job
          uses: actions/download-artifact@v2
          with: 
            name: output-log-file
        - shell: bash
          run: |
            value=`cat output-log-file`
            echo The result is $value
